[project]
name = "aladin"
version = "1.0.0"
requires-python = ">=3.11,<3.15"
description = "Aladin is a framework for ambulatory and clinical ECG processing, delineation, analysis, and diagnosis"
authors = [
    { name = "Lukas P.A. Arts"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    'ecg',
    'delineation',
    'segmentation',
    'diagnosis',
    'arrhythmia',
    'ambulatory',
    'deep learning'
]
dependencies = [
	"torch>=2.10,<3",
	
    "acvl-utils>=0.2.6,<0.3",
    "dynamic-network-architectures>=0.3.1,<0.4",

    "tqdm>=4.67,<5",
    "seaborn>=0.13,<1",
    "dicom2nifti>=2.6,<3",

    "batchgenerators>=0.25.3,<0.26",
    "batchgeneratorsv2>=0.3.5,<0.4",

    "scikit-image>=0.26,<0.27",
    "SimpleITK>=2.5.5,<3",

    "google-cloud-storage>=3,<4",
    "google-cloud-bigquery>=3,<4",
    "boto3>=1.40,<2",

    "openpyxl>=3.1,<4",

    "neurokit2>=0.2.12,<0.3",
    "wfdb>=4.3,<5",

    "scipy>=1.18,<2",
    "numpy>=2.0,<3",
    "scikit-learn>=1.9,<2",

    "psutil>=7,<8",

    "rich>=14,<15",

    "dtw-python>=1.7.5,<2",

    "pandas>=2.2,<4",
    "matplotlib>=3.10,<4",

    "pymongo>=4.17,<5",

    "huggingface-hub>=1,<2",

    "graphviz>=0.20,<1",
    "tifffile>=2025.6",
    "requests>=2.32,<3",
    "nibabel>=5.3,<6",
    "yacs>=0.1.8,<1",
    "einops>=0.8,<1"
]          

[project.optional-dependencies]
dev = [
    "pytest>=8,<9",
]          

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11", "torch"]
build-backend = "scikit_build_core.build"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
#
# ignore-words-list = ''

[tool.scikit-build]
minimum-version = "build-system.requires"

[tool.scikit-build.wheel.packages]
aladin = "aladin/src/aladin"
nnunetv2 = "nnUNet/nnunetv2"

[tool.scikit-build.sdist]
include = [
    "aladin/**",
    "nnUNet/**",
    "CMakeLists.txt",
]
