
nnUNetv2_train 117 1d_decoding 0 -p nnUNetWithClassificationPlans -tr nnUNetWithClassificationTrainer 
nnUNetv2_train 117 1d_decoding 1 -p nnUNetWithClassificationPlans -tr nnUNetWithClassificationTrainer 
nnUNetv2_train 117 1d_decoding 2 -p nnUNetWithClassificationPlans -tr nnUNetWithClassificationTrainer
nnUNetv2_train 117 1d_decoding 3 -p nnUNetWithClassificationPlans -tr nnUNetWithClassificationTrainer
nnUNetv2_train 117 1d_decoding 4 -p nnUNetWithClassificationPlans -tr nnUNetWithClassificationTrainer

nnUNetv2_train 201 1d_decoding 0 -p nnUNetWithClassificationPlans -tr ClassificationTrainer -pretrained_weights $nnUNet_results/Dataset117_nnunet_17/nnUNetWithClassificationTrainer__nnUNetWithClassificationPlans__1d_decoding/fold_0/checkpoint_best.pth
nnUNetv2_train 201 1d_decoding 1 -p nnUNetWithClassificationPlans -tr ClassificationTrainer -pretrained_weights $nnUNet_results/Dataset117_nnunet_17/nnUNetWithClassificationTrainer__nnUNetWithClassificationPlans__1d_decoding/fold_1/checkpoint_best.pth
nnUNetv2_train 201 1d_decoding 2 -p nnUNetWithClassificationPlans -tr ClassificationTrainer -pretrained_weights $nnUNet_results/Dataset117_nnunet_17/nnUNetWithClassificationTrainer__nnUNetWithClassificationPlans__1d_decoding/fold_2/checkpoint_best.pth
nnUNetv2_train 201 1d_decoding 3 -p nnUNetWithClassificationPlans -tr ClassificationTrainer -pretrained_weights $nnUNet_results/Dataset117_nnunet_17/nnUNetWithClassificationTrainer__nnUNetWithClassificationPlans__1d_decoding/fold_3/checkpoint_best.pth
nnUNetv2_train 201 1d_decoding 4 -p nnUNetWithClassificationPlans -tr ClassificationTrainer -pretrained_weights $nnUNet_results/Dataset117_nnunet_17/nnUNetWithClassificationTrainer__nnUNetWithClassificationPlans__1d_decoding/fold_4/checkpoint_best.pth