[project]
name = "aladin"
version = "1.1.0"
requires-python = ">=3.9"
description = "Aladin is a framework for ambulatory ECG delineation and diagnosis"
authors = [
    { name = "anonymous"},
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    'ecg',
    'delineation',
    'segmentation',
    'diagnosis',
    'arrhythmia',
    'ambulatory',
    'deep learning'
]
dependencies = [
    "setuptools<82.0.0",
    "torch",
    "google-cloud-storage",
    "google-cloud-bigquery",
    "boto3",
    "openpyxl",
    "neurokit2",
    "ruptures",
    "neurokit2==0.2.10",
    "wfdb==4.1.2",
    "tqdm==4.67.0",
    "scipy",
    "numpy",
    "rich==13.9.4",
    "baal==2.1.0",
    "dtw-python==1.5.3",
    "pandas==2.2.3",
    "matplotlib==3.9.2",
    "pymongo==4.10.1",
    "huggingface_hub"
]

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
#
# ignore-words-list = ''
